# Installing Putty on ubuntu 22.04
- name: Installing putty on ubuntu 22.04
  hosts: localhost
  become: true
  tasks:
    #- name: Update and upgrade
    #  apt:
    #    update_cache: yes
          
    - name: Installing Putty
      apt:
        name:
          - putty
          - putty-tools
        state: present
    
    #- name: Removing putty
    #  apt:
    #    name:
    #      - putty
    #      - putty-tools
    #    state: absent

